# Generated by Django 3.2.16 on 2022-12-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20221224_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(through='catalogue.ProductCategory', to='catalogue.category', verbose_name='Categories'),
        ),
    ]
